import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { getDal } from "../../dal";
import type { Lead, LeadStage } from "../../dal/types";
import { useRole } from "../../app/RoleContext";
import { currentTime } from "../../lib/clock";
import type {
  CrmAutomation, CrmActionKind, CrmTriggerKind, CrmTask, CrmTaskPriority,
} from "./_data/types";
import { CRM_AUTOMATIONS_KEY, CRM_TASKS_KEY } from "./_data/keys";
import { CRM_AUTOMATIONS_SEED, CRM_TASKS_SEED } from "./_data/seeds";
import { daysBetween, leadLabel, STAGE_LABELS, todayIso } from "./_data/util";

/**
 * CRM · Automations — follow-up rules that surface leads needing attention.
 * A rule pairs a trigger (lead sits in a stage N days / no activity N days /
 * event N days out) with an action (create a task / reminder). Rules persist
 * to dal.settings["crm.automations"]. Matches are computed LIVE from dal.leads
 * (no background execution); a matching rule can spawn tasks into "crm.tasks".
 * Source: Manus CrmAutomations.tsx.
 */

type Sync = "idle" | "saving" | "saved" | "error";

const TRIGGERS: Array<{ id: CrmTriggerKind; label: string }> = [
  { id: "stage_dwell", label: "Lead sits in stage for N days" },
  { id: "no_activity", label: "No activity logged for N days" },
  { id: "event_approaching", label: "Event is within N days" },
];
const ACTIONS: Array<{ id: CrmActionKind; label: string }> = [
  { id: "create_task", label: "Create a follow-up task" },
  { id: "reminder", label: "Create a reminder task" },
];
const STAGES = Object.keys(STAGE_LABELS) as LeadStage[];
const PRIORITIES: CrmTaskPriority[] = ["low", "normal", "high", "urgent"];

/** Leads currently matching a rule, evaluated against the business clock. */
function matchingLeads(rule: CrmAutomation, leads: Lead[], today: string): Lead[] {
  const now = currentTime().toISOString();
  return leads.filter(l => {
    if (rule.trigger === "event_approaching") {
      if (l.stage === "lost") return false;
      if (!l.eventDate) return false;
      const out = daysBetween(today, l.eventDate);
      return out >= 0 && out <= rule.days;
    }
    if (l.stage !== rule.stage) return false;
    if (rule.trigger === "stage_dwell") {
      return daysBetween(l.updatedAt, now) >= rule.days;
    }
    // no_activity: days since the most recent activity entry (fall back to updatedAt)
    const lastAt = l.activity.length > 0
      ? l.activity.reduce((m, a) => (a.at > m ? a.at : m), l.activity[0].at)
      : l.updatedAt;
    return daysBetween(lastAt, now) >= rule.days;
  });
}

export function CrmAutomations() {
  const { actor } = useRole();
  const dal = getDal();
  const qc = useQueryClient();
  const [sync, setSync] = useState<Sync>("idle");
  const [editing, setEditing] = useState<CrmAutomation | "new" | null>(null);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const { data: rules = [], isLoading } = useQuery({
    queryKey: ["settings", CRM_AUTOMATIONS_KEY],
    queryFn: () => dal.settings.get<CrmAutomation[]>(CRM_AUTOMATIONS_KEY, CRM_AUTOMATIONS_SEED),
  });
  const { data: leads = [] } = useQuery({ queryKey: ["leads", "list"], queryFn: () => dal.leads.list() });

  const saveRules = useMutation({
    mutationFn: (next: CrmAutomation[]) => {
      setSync("saving");
      return dal.settings.set(CRM_AUTOMATIONS_KEY, next, actor).then(
        () => { setSync("saved"); return next; },
        e => { setSync("error"); throw e; },
      );
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["settings", CRM_AUTOMATIONS_KEY] }),
  });

  // Spawns one task per matching lead (skipping leads that already have an open
  // task from this rule) into the shared "crm.tasks" bucket.
  const spawnTasks = useMutation({
    mutationFn: async ({ rule, matches }: { rule: CrmAutomation; matches: Lead[] }) => {
      setSync("saving");
      const existing = await dal.settings.get<CrmTask[]>(CRM_TASKS_KEY, CRM_TASKS_SEED);
      const now = currentTime().toISOString();
      const additions: CrmTask[] = [];
      for (const lead of matches) {
        const already = existing.some(t => !t.done && t.createdBy === rule.id && t.leadId === lead.id);
        if (already) continue;
        additions.push({
          id: `task-${rule.id}-${lead.id}-${Date.now()}`,
          title: rule.taskTitle.replace("{lead}", lead.name),
          dueDate: todayIso(),
          priority: rule.taskPriority,
          done: false,
          leadId: lead.id,
          linkedLabel: leadLabel(lead),
          notes: `Auto-generated by rule "${rule.name}".`,
          createdBy: rule.id,
          createdAt: now,
          updatedAt: now,
        });
      }
      const next = [...additions, ...existing];
      return dal.settings.set(CRM_TASKS_KEY, next, actor).then(
        () => { setSync("saved"); return additions.length; },
        e => { setSync("error"); throw e; },
      );
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["settings", CRM_TASKS_KEY] }),
  });

  const today = todayIso();
  const matchesByRule = useMemo(() => {
    const m: Record<string, Lead[]> = {};
    for (const r of rules) m[r.id] = matchingLeads(r, leads, today);
    return m;
  }, [rules, leads, today]);

  function upsert(input: Omit<CrmAutomation, "createdAt" | "updatedAt" | "id"> & { id?: string }) {
    const now = currentTime().toISOString();
    const existing = input.id ? rules.find(r => r.id === input.id) : undefined;
    const rec: CrmAutomation = {
      id: input.id ?? `auto-${Date.now()}`,
      name: input.name,
      enabled: input.enabled,
      trigger: input.trigger,
      stage: input.stage,
      days: input.days,
      action: input.action,
      taskTitle: input.taskTitle,
      taskPriority: input.taskPriority,
      createdAt: existing?.createdAt ?? now,
      updatedAt: now,
    };
    saveRules.mutate(existing ? rules.map(r => (r.id === rec.id ? rec : r)) : [rec, ...rules]);
    setEditing(null);
  }
  function toggle(r: CrmAutomation) {
    saveRules.mutate(rules.map(x => (x.id === r.id ? { ...x, enabled: !x.enabled, updatedAt: currentTime().toISOString() } : x)));
  }
  function remove(id: string) {
    saveRules.mutate(rules.filter(r => r.id !== id));
  }

  if (isLoading) return <p className="py-20 text-center text-zinc-500">Loading automations…</p>;

  return (
    <div className="mx-auto max-w-4xl pt-6 pb-12">
      <header className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-black uppercase text-zinc-100">Automations</h1>
          <p className="text-sm text-zinc-500">{rules.filter(r => r.enabled).length} of {rules.length} rules active</p>
        </div>
        <div className="flex items-center gap-2">
          <SyncBadge sync={sync} />
          <button onClick={() => setEditing("new")}
            className="min-h-[44px] rounded-lg bg-fire px-4 py-2 text-sm font-bold text-white">+ New Rule</button>
        </div>
      </header>

      {rules.length === 0 ? (
        <p className="py-16 text-center text-zinc-500">No rules yet — create your first follow-up rule.</p>
      ) : (
        <ul className="mt-4 space-y-3">
          {rules.map(r => {
            const matches = matchesByRule[r.id] ?? [];
            const expanded = expandedId === r.id;
            const trigger = TRIGGERS.find(t => t.id === r.trigger)?.label ?? r.trigger;
            const action = ACTIONS.find(a => a.id === r.action)?.label ?? r.action;
            return (
              <li key={r.id} className="rounded-2xl border border-ink-700 bg-ink-900 p-4">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div className="min-w-0">
                    <div className="flex items-center gap-2">
                      <p className="font-bold text-zinc-100">{r.name}</p>
                      <span className={`rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide ${
                        r.enabled ? "border-emerald-700/50 text-emerald-300" : "border-ink-700 text-zinc-500"
                      }`}>{r.enabled ? "Active" : "Off"}</span>
                    </div>
                    <p className="mt-1 text-sm text-zinc-400">
                      <span className="text-zinc-500">When</span> {trigger.replace("N", String(r.days))}
                      {r.trigger !== "event_approaching" ? ` · stage ${STAGE_LABELS[r.stage]}` : ""}
                    </p>
                    <p className="text-sm text-zinc-400"><span className="text-zinc-500">Then</span> {action}</p>
                  </div>
                  <div className="flex shrink-0 items-center gap-2">
                    <button onClick={() => toggle(r)}
                      className={`min-h-[44px] rounded-lg border px-3 py-2 text-sm font-semibold ${
                        r.enabled ? "border-emerald-700/50 bg-ink-800 text-emerald-300" : "border-ink-700 bg-ink-800 text-zinc-400"
                      }`}>{r.enabled ? "Disable" : "Enable"}</button>
                    <button onClick={() => setEditing(r)}
                      className="min-h-[44px] rounded-lg border border-ink-700 bg-ink-800 px-3 py-2 text-sm font-semibold text-zinc-300">Edit</button>
                    <button onClick={() => remove(r.id)}
                      className="min-h-[44px] rounded-lg border border-red-800/60 bg-ink-800 px-3 py-2 text-sm font-semibold text-red-400">Delete</button>
                  </div>
                </div>

                <div className="mt-3 flex flex-wrap items-center justify-between gap-2 rounded-xl border border-ink-700 bg-ink-950/50 p-3">
                  <button onClick={() => setExpandedId(expanded ? null : r.id)}
                    className="text-sm font-semibold text-sky-300">
                    {matches.length} matching lead{matches.length === 1 ? "" : "s"} {expanded ? "▲" : "▼"}
                  </button>
                  <button onClick={() => spawnTasks.mutate({ rule: r, matches })}
                    disabled={spawnTasks.isPending || matches.length === 0}
                    className="min-h-[44px] rounded-lg bg-fire px-4 py-2 text-sm font-bold text-white disabled:opacity-40">
                    Run now → create tasks
                  </button>
                </div>
                {expanded && (
                  <ul className="mt-2 space-y-1">
                    {matches.length === 0 ? (
                      <li className="px-2 py-2 text-sm text-zinc-500">No leads currently match this rule.</li>
                    ) : matches.map(l => (
                      <li key={l.id} className="rounded-lg border border-ink-700 bg-ink-800/60 px-3 py-2 text-sm text-zinc-200">
                        {leadLabel(l)} <span className="text-zinc-500">· {STAGE_LABELS[l.stage]}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </li>
            );
          })}
        </ul>
      )}

      {editing && (
        <RuleDialog rule={editing === "new" ? null : editing} busy={saveRules.isPending}
          onCancel={() => setEditing(null)} onSubmit={upsert} />
      )}
    </div>
  );
}

function RuleDialog({ rule, busy, onCancel, onSubmit }: {
  rule: CrmAutomation | null; busy: boolean; onCancel: () => void;
  onSubmit: (input: Omit<CrmAutomation, "createdAt" | "updatedAt" | "id"> & { id?: string }) => void;
}) {
  const [name, setName] = useState(rule?.name ?? "");
  const [enabled, setEnabled] = useState(rule?.enabled ?? true);
  const [trigger, setTrigger] = useState<CrmTriggerKind>(rule?.trigger ?? "stage_dwell");
  const [stage, setStage] = useState<LeadStage>(rule?.stage ?? "new");
  const [days, setDays] = useState(String(rule?.days ?? 3));
  const [action, setAction] = useState<CrmActionKind>(rule?.action ?? "create_task");
  const [taskTitle, setTaskTitle] = useState(rule?.taskTitle ?? "Follow up with {lead}");
  const [taskPriority, setTaskPriority] = useState<CrmTaskPriority>(rule?.taskPriority ?? "normal");

  function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!name.trim() || !taskTitle.trim()) return;
    onSubmit({
      id: rule?.id,
      name: name.trim(),
      enabled,
      trigger,
      stage,
      days: Math.max(0, Math.round(Number(days) || 0)),
      action,
      taskTitle: taskTitle.trim(),
      taskPriority,
    });
  }

  return (
    <div role="dialog" aria-modal="true" aria-label={rule ? "Edit rule" : "New rule"}
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" onClick={onCancel}>
      <form onClick={e => e.stopPropagation()} onSubmit={submit}
        className="w-full max-w-md rounded-2xl border border-ink-700 bg-ink-900 p-5">
        <h2 className="text-xl font-black text-zinc-100">{rule ? "Edit rule" : "New rule"}</h2>
        <label className="mt-4 block text-xs font-semibold uppercase tracking-wider text-zinc-500">Name
          <input value={name} onChange={e => setName(e.target.value)} autoFocus placeholder="e.g. Nudge stale new leads"
            className="mt-1 w-full rounded-lg border border-ink-700 bg-ink-800 px-3 py-2.5 text-sm text-zinc-100" />
        </label>
        <label className="mt-3 block text-xs font-semibold uppercase tracking-wider text-zinc-500">Trigger
          <select value={trigger} onChange={e => setTrigger(e.target.value as CrmTriggerKind)}
            className="mt-1 w-full rounded-lg border border-ink-700 bg-ink-800 px-2 py-2.5 text-sm text-zinc-100">
            {TRIGGERS.map(t => <option key={t.id} value={t.id}>{t.label}</option>)}
          </select>
        </label>
        <div className="mt-3 grid grid-cols-2 gap-3">
          <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-500">Days threshold
            <input type="number" min={0} value={days} onChange={e => setDays(e.target.value)}
              className="mt-1 w-full rounded-lg border border-ink-700 bg-ink-800 px-3 py-2.5 text-sm text-zinc-100" />
          </label>
          <label className={`block text-xs font-semibold uppercase tracking-wider text-zinc-500 ${trigger === "event_approaching" ? "opacity-40" : ""}`}>Stage
            <select value={stage} disabled={trigger === "event_approaching"} onChange={e => setStage(e.target.value as LeadStage)}
              className="mt-1 w-full rounded-lg border border-ink-700 bg-ink-800 px-2 py-2.5 text-sm text-zinc-100">
              {STAGES.map(s => <option key={s} value={s}>{STAGE_LABELS[s]}</option>)}
            </select>
          </label>
        </div>
        <label className="mt-3 block text-xs font-semibold uppercase tracking-wider text-zinc-500">Action
          <select value={action} onChange={e => setAction(e.target.value as CrmActionKind)}
            className="mt-1 w-full rounded-lg border border-ink-700 bg-ink-800 px-2 py-2.5 text-sm text-zinc-100">
            {ACTIONS.map(a => <option key={a.id} value={a.id}>{a.label}</option>)}
          </select>
        </label>
        <label className="mt-3 block text-xs font-semibold uppercase tracking-wider text-zinc-500">Task title (use {"{lead}"})
          <input value={taskTitle} onChange={e => setTaskTitle(e.target.value)}
            className="mt-1 w-full rounded-lg border border-ink-700 bg-ink-800 px-3 py-2.5 text-sm text-zinc-100" />
        </label>
        <div className="mt-3 flex items-center justify-between gap-3">
          <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-500">Task priority
            <select value={taskPriority} onChange={e => setTaskPriority(e.target.value as CrmTaskPriority)}
              className="mt-1 rounded-lg border border-ink-700 bg-ink-800 px-2 py-2.5 text-sm text-zinc-100">
              {PRIORITIES.map(p => <option key={p} value={p}>{p}</option>)}
            </select>
          </label>
          <label className="mt-4 flex items-center gap-2 text-sm text-zinc-300">
            <input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} className="h-4 w-4" />
            Enabled
          </label>
        </div>
        <div className="mt-5 flex justify-end gap-2">
          <button type="button" onClick={onCancel}
            className="min-h-[44px] rounded-lg border border-ink-700 bg-ink-800 px-4 py-2 text-sm font-semibold text-zinc-300">Cancel</button>
          <button type="submit" disabled={busy || !name.trim() || !taskTitle.trim()}
            className="min-h-[44px] rounded-lg bg-fire px-4 py-2 text-sm font-bold text-white disabled:opacity-50">
            {busy ? "Saving…" : "Save rule"}
          </button>
        </div>
      </form>
    </div>
  );
}

function SyncBadge({ sync }: { sync: Sync }) {
  const meta: Record<Sync, { label: string; cls: string }> = {
    idle: { label: "Up to date", cls: "text-zinc-500 border-ink-700" },
    saving: { label: "Saving…", cls: "text-amber-400 border-amber-700/50" },
    saved: { label: "Saved ✓", cls: "text-green-400 border-green-700/50" },
    error: { label: "Save failed — retry", cls: "text-red-400 border-red-700/50" },
  };
  return <span role="status" className={`rounded-lg border bg-ink-900 px-3 py-2 text-xs font-semibold ${meta[sync].cls}`}>{meta[sync].label}</span>;
}
