const modules = [
  {id:'v2',icon:'🚀',title:'Fire Sheet V2 (Full App)',desc:'The complete rebuild: every module live with demo data.',live:true},
  {id:'kitchen',icon:'🔪',title:'Kitchen',desc:'Cook, catering execution and prep systems.',live:false},
  {id:'seminole',icon:'🏠',title:'Seminole Heights',desc:'Front of house and weekend Fire Drop orders.',live:true},
  {id:'pit',icon:'🔥',title:'Pit',desc:'Smoker schedule and pitmaster command.',live:false},
  {id:'catering',icon:'🍽️',title:'Catering',desc:'Director cockpit, leads, BEOs and pull sheets.',live:true},
  {id:'marketing',icon:'📣',title:'Marketing',desc:'Content, attribution, ads and AI tools.',live:false},
  {id:'packing',icon:'📦',title:'Packing',desc:'Hot box checkout and packing slips.',live:false},
  {id:'admin',icon:'⚙️',title:'Admin',desc:'Settings, menus, users and brand controls.',live:false},
  {id:'portal',icon:'🤝',title:'Client Portal',desc:'Client orders, contracts and portal admin.',live:false},
];

const menu = [
  {id:'oxtail-half',cat:'Signature',name:'Tampa Diamonds · ½ lb',desc:'Guava glazed smoked oxtail. Limited weekly feature.',price:23},
  {id:'oxtail-lb',cat:'Signature',name:'Tampa Diamonds · 1 lb',desc:'Guava glazed smoked oxtail. Limited weekly feature.',price:45.99},
  {id:'party-10',cat:'Samplers',name:'Party Sampler · Feeds 10',desc:'A full Station House spread built for the crew.',price:269},
  {id:'party-20',cat:'Samplers',name:'Party Sampler · Feeds 20',desc:'Pit-smoked meats, sides, sauces and bread.',price:569},
  {id:'ribs',cat:'Meats',name:'St. Louis Ribs · Full Rack',desc:'Slow smoked, glazed and sliced to order.',price:34},
  {id:'pork',cat:'Meats',name:'Pulled Pork · 1 lb',desc:'Oak smoked, hand pulled and lightly sauced.',price:19},
  {id:'mac',cat:'Sides',name:'Mac & Cheese · Pint',desc:'Creamy house mac with toasted cheese top.',price:12},
  {id:'pudding',cat:'Dessert',name:'Banana Pudding · Pint',desc:'Classic banana pudding with vanilla wafers.',price:14},
];

const seedOrders = [
  {id:'FD-0717-1042',name:'Maria Santos',phone:'813-555-0184',email:'maria@example.com',day:'Friday',time:'11AM–12PM',items:'Tampa Diamonds × 2, Mac & Cheese × 1',total:58,paid:true,status:'active'},
  {id:'FD-0717-1061',name:'James Walker',phone:'813-555-0119',email:'james@example.com',day:'Friday',time:'12–1PM',items:'Party Sampler · Feeds 10 × 1',total:289.18,paid:true,status:'active'},
  {id:'FD-0718-1088',name:'Aisha Brooks',phone:'727-555-0172',email:'aisha@example.com',day:'Saturday',time:'1–2PM',items:'Ribs × 2, Pulled Pork × 1',total:93.53,paid:false,status:'active'},
  {id:'FD-0718-1094',name:'Evan Reed',phone:'813-555-0147',email:'evan@example.com',day:'Saturday',time:'2–3PM',items:'Tampa Diamonds × 1',total:49.44,paid:true,status:'complete'},
];

const seedLeads = [
  {id:1,name:'Kara Mills',company:'Bayfront Realty',event:'Corporate lunch · 80 guests',value:3200,source:'google',stage:'New Lead'},
  {id:2,name:'Derek Owens',company:'',event:'Wedding · 120 guests',value:6800,source:'facebook',stage:'Contacted'},
  {id:3,name:'Samantha Lee',company:'Tampa Tech',event:'Company picnic · 200 guests',value:9400,source:'referral',stage:'Quote Sent'},
  {id:4,name:'Luis Ramirez',company:'',event:'Graduation · 60 guests',value:2400,source:'organic',stage:'Follow-Up'},
  {id:5,name:'Megan Ford',company:'Ford Marine',event:'Holiday party · 150 guests',value:7200,source:'direct',stage:'Booked'},
  {id:6,name:'Tyrell King',company:'',event:'Birthday · 40 guests',value:1300,source:'facebook',stage:'Lost'},
];

const stages = ['New Lead','Contacted','Quote Sent','Follow-Up','Booked','Lost'];
const state = {
  route: location.hash.slice(1) || 'home',
  cart: {},
  orders: JSON.parse(localStorage.getItem('firesheet.orders') || 'null') || seedOrders,
  leads: JSON.parse(localStorage.getItem('firesheet.leads') || 'null') || seedLeads,
  orderTab:'active', orderSearch:'', dayFilter:'all', sourceFilter:'all'
};

const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const escapeHTML = s => String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(){ localStorage.setItem('firesheet.orders',JSON.stringify(state.orders)); localStorage.setItem('firesheet.leads',JSON.stringify(state.leads)); }
function go(route){ location.hash=route; }
function toast(msg){ const el=document.querySelector('#toast'); el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2200); }

function layout(content){
  const active=state.route;
  return `<div class="shell"><header class="topbar">
    <div class="brand" onclick="go('home')"><div class="mark"><span>SH</span></div><div><div class="brand-title">Station House BBQ</div><div class="brand-sub">Operations · Fire Sheet</div></div></div>
    <nav class="nav"><button class="${active==='home'?'active':''}" onclick="go('home')">Hub</button><button class="${active==='drop'?'active':''}" onclick="go('drop')">Fire Drop</button><button class="${active==='seminole'?'active':''}" onclick="go('seminole')">Preorders</button><button class="${active==='catering'?'active':''}" onclick="go('catering')">Leads</button></nav>
  </header>${content}<footer class="footer">Station House BBQ · Tampa, FL · Demo environment</footer></div>`;
}

function home(){ return layout(`<main class="container"><section class="hero"><div class="eyebrow">Station House Command Center</div><h1>Where do you want <span class="orange">to go?</span></h1><p>One connected operations hub for the restaurant, catering, weekend drops and the crew behind it all.</p></section><section class="module-grid">${modules.map(m=>`<article class="module-card" onclick="openModule('${m.id}',${m.live})"><div class="module-icon">${m.icon}</div><h3>${m.title}</h3><p>${m.desc}</p><div class="card-bottom"><span class="badge ${m.live?'live':'soon'}">● ${m.live?'LIVE':'SOON'}</span><span class="open">${m.live?'Open →':'Preview'}</span></div></article>`).join('')}</section></main>`); }
function openModule(id,live){ if(id==='v2'){location.href='v2/';return;} if(!live) return toast('This module is queued for the next build phase.'); go(id); }

function drop(){
  const quantities=Object.values(state.cart).reduce((a,b)=>a+b,0);
  return layout(`<main class="container"><section class="drop-hero"><div><div class="eyebrow">This Weekend's Limited Fire Drop</div><h1>Tampa <span class="orange">Diamonds</span></h1><p>Guava glazed, oak-smoked oxtail—built low and slow by the Station House crew. Reserve Friday or Saturday pickup before the cutoff.</p><div class="countdown"><div><strong id="cd-days">01</strong><span>Days</span></div><div><strong id="cd-hours">12</strong><span>Hours</span></div><div><strong id="cd-mins">34</strong><span>Minutes</span></div><div><strong id="cd-secs">18</strong><span>Seconds</span></div></div><div class="inventory">🔥 Only 20 lbs available for this drop</div><button class="btn" onclick="document.querySelector('#drop-menu').scrollIntoView()">Reserve Yours Now</button></div></section>
  <section id="drop-menu" class="menu-layout"><div><div class="page-head"><div><div class="eyebrow">Build Your Order</div><h2>The Weekend Menu</h2></div><p>Friday & Saturday pickup</p></div><div class="menu-list">${menu.map(i=>{const q=state.cart[i.id]||0;return `<article class="menu-item"><div><span class="eyebrow" style="font-size:8px">${i.cat}</span><h4>${i.name}</h4><p>${i.desc}</p><div class="qty"><button onclick="changeQty('${i.id}',-1)">−</button><strong>${q}</strong><button onclick="changeQty('${i.id}',1)">+</button></div></div><div class="price">${money(i.price)}</div></article>`}).join('')}</div></div>${cartMarkup(quantities)}</section></main>`);
}
function cartMarkup(count){ const rows=menu.filter(i=>state.cart[i.id]).map(i=>`<div class="cart-row"><span>${i.name} × ${state.cart[i.id]}</span><strong>${money(i.price*state.cart[i.id])}</strong></div>`).join(''); const sub=cartSubtotal(); const tax=sub*.075; return `<aside class="cart"><h3>Your Order</h3>${rows||'<div class="empty" style="padding:25px 0">Add items to get started.</div>'}${count?`<div class="cart-row"><span>Subtotal</span><span>${money(sub)}</span></div><div class="cart-row"><span>Tax · 7.5%</span><span>${money(tax)}</span></div><div class="total-row"><span>Total</span><span>${money(sub+tax)}</span></div><button class="btn" onclick="go('checkout')">Checkout · ${count} item${count===1?'':'s'}</button>`:''}<div class="notice">Demo checkout only. No card will be charged.</div></aside>`; }
function cartSubtotal(){ return menu.reduce((sum,i)=>sum+(state.cart[i.id]||0)*i.price,0); }
function changeQty(id,delta){ state.cart[id]=Math.max(0,(state.cart[id]||0)+delta); render(); }

function checkout(){ if(!cartSubtotal()) return drop(); return layout(`<main class="container checkout"><div class="page-head"><div><div class="eyebrow">Secure Your Pickup</div><h2>Checkout</h2><p>Customer info → Pickup window → Confirmation</p></div></div><section class="panel"><form id="checkout-form" onsubmit="placeOrder(event)"><div class="form-grid"><label>Full name<input name="name" required placeholder="First and last name"></label><label>Phone<input name="phone" required type="tel" placeholder="(813) 555-0123"></label><label class="full">Email<input name="email" required type="email" placeholder="you@example.com"></label><label>Pickup day<select name="day" required><option>Friday</option><option>Saturday</option></select></label><label>Pickup window<select name="time" required><option>11AM–12PM</option><option>12–1PM</option><option>1–2PM</option><option>2–3PM</option></select></label><label class="full">Tip<select name="tip"><option value="0">No tip</option><option value=".15">15%</option><option value=".20">20%</option><option value=".25">25%</option></select></label></div><div class="notice">This is a test environment. The payment step is simulated and no financial information is collected.</div><div class="total-row"><span>Order total</span><span>${money(cartSubtotal()*1.075)}</span></div><button class="btn" style="width:100%">Place Demo Order</button></form></section></main>`); }
function placeOrder(e){ e.preventDefault(); const fd=new FormData(e.target); const sub=cartSubtotal(); const tip=sub*Number(fd.get('tip')); const tax=sub*.075; const id=`FD-${new Date().toISOString().slice(5,10).replace('-','')}-${Math.floor(1000+Math.random()*8999)}`; state.orders.unshift({id,name:fd.get('name'),phone:fd.get('phone'),email:fd.get('email'),day:fd.get('day'),time:fd.get('time'),items:menu.filter(i=>state.cart[i.id]).map(i=>`${i.name} × ${state.cart[i.id]}`).join(', '),total:sub+tax+tip,paid:true,status:'active'}); save(); state.cart={}; sessionStorage.setItem('lastOrder',id); go('confirmation'); }
function confirmation(){ const id=sessionStorage.getItem('lastOrder')||'FD-DEMO-1000'; const o=state.orders.find(x=>x.id===id); return layout(`<main class="container checkout"><section class="panel success"><div class="check">✓</div><div class="eyebrow">Order Confirmed</div><h2>You're on the Fire Sheet.</h2><p class="muted">Reference <strong style="color:white">${id}</strong></p>${o?`<p>Pickup: <strong>${o.day}, ${o.time}</strong><br>${escapeHTML(o.items)}</p>`:''}<button class="btn" onclick="go('drop')">Back to Fire Drop</button></section></main>`); }

function seminole(){ const visible=state.orders.filter(o=>o.status===state.orderTab).filter(o=>state.dayFilter==='all'||o.day===state.dayFilter).filter(o=>`${o.name} ${o.phone} ${o.id} ${o.items}`.toLowerCase().includes(state.orderSearch.toLowerCase())).sort((a,b)=>`${a.day}${a.time}`.localeCompare(`${b.day}${b.time}`)); const active=state.orders.filter(o=>o.status==='active'); const revenue=active.reduce((s,o)=>s+o.total,0); return layout(`<main class="container"><div class="page-head"><div><div class="eyebrow">Seminole Heights</div><h2>Weekend Preorders</h2><p>Floor-friendly pickup command center.</p></div><button class="btn" onclick="go('drop')">+ Demo Order</button></div><section class="stats"><div class="stat"><span>Active pickups</span><strong>${active.length}</strong></div><div class="stat"><span>Friday</span><strong>${active.filter(o=>o.day==='Friday').length}</strong></div><div class="stat"><span>Saturday</span><strong>${active.filter(o=>o.day==='Saturday').length}</strong></div><div class="stat"><span>Active revenue</span><strong>${money(revenue)}</strong></div></section><div class="tabs"><button class="${state.orderTab==='active'?'active':''}" onclick="setOrderTab('active')">Active</button><button class="${state.orderTab==='complete'?'active':''}" onclick="setOrderTab('complete')">Completed / History</button></div><div class="toolbar"><input class="field search" placeholder="Search name, phone or order #" value="${escapeHTML(state.orderSearch)}" oninput="setOrderSearch(this.value)"><select onchange="setDayFilter(this.value)"><option value="all">All pickup days</option><option ${state.dayFilter==='Friday'?'selected':''}>Friday</option><option ${state.dayFilter==='Saturday'?'selected':''}>Saturday</option></select></div><section class="panel table-wrap">${visible.length?`<table><thead><tr><th>Pickup</th><th>Customer</th><th>Order</th><th>Total</th><th>Payment</th><th>Action</th></tr></thead><tbody>${visible.map(o=>`<tr><td><strong>${o.day}</strong><br><span class="muted">${o.time}</span></td><td class="customer"><strong>${escapeHTML(o.name)}</strong><span>${escapeHTML(o.phone)}<br>${escapeHTML(o.email)}</span></td><td class="order-items"><strong>${o.id}</strong><span>${escapeHTML(o.items)}</span></td><td><strong>${money(o.total)}</strong></td><td><span class="status ${o.paid?'paid':'pending'}">${o.paid?'Paid':'Pending'}</span></td><td>${o.status==='active'?`<button class="btn small" onclick="completeOrder('${o.id}')">Mark Picked Up</button>`:`<button class="btn secondary small" onclick="reopenOrder('${o.id}')">Restore</button>`}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No orders match these filters.</div>'}</section></main>`); }
function setOrderTab(v){state.orderTab=v;render()} function setOrderSearch(v){state.orderSearch=v;render()} function setDayFilter(v){state.dayFilter=v;render()} function completeOrder(id){const o=state.orders.find(x=>x.id===id);o.status='complete';save();render();toast('Order moved to pickup history.')} function reopenOrder(id){const o=state.orders.find(x=>x.id===id);o.status='active';save();render();toast('Order restored to active pickups.')}

function catering(){ const filtered=state.leads.filter(l=>state.sourceFilter==='all'||l.source===state.sourceFilter); const total=filtered.reduce((s,l)=>s+l.value,0); return layout(`<main class="container"><div class="page-head"><div><div class="eyebrow">Catering Director Cockpit</div><h2>Lead Pipeline</h2><p>Native attribution from first click through booked event.</p></div><button class="btn" onclick="addLead()">+ Add Demo Lead</button></div><section class="stats"><div class="stat"><span>Total opportunities</span><strong>${filtered.length}</strong></div><div class="stat"><span>Pipeline value</span><strong>${money(total)}</strong></div><div class="stat"><span>Booked</span><strong>${filtered.filter(l=>l.stage==='Booked').length}</strong></div><div class="stat"><span>Needs follow-up</span><strong>${filtered.filter(l=>['New Lead','Contacted','Quote Sent','Follow-Up'].includes(l.stage)).length}</strong></div></section><div class="toolbar"><select onchange="setSource(this.value)"><option value="all">All sources</option>${['facebook','google','organic','direct','referral'].map(s=>`<option value="${s}" ${state.sourceFilter===s?'selected':''}>${s[0].toUpperCase()+s.slice(1)}</option>`).join('')}</select><span class="muted" style="align-self:center">Drag cards between stages</span></div><section class="kanban">${stages.map(stage=>{const leads=filtered.filter(l=>l.stage===stage);return `<div class="column" ondragover="event.preventDefault()" ondrop="dropLead(event,'${stage}')"><div class="column-head"><strong>${stage}</strong><span>${leads.length} · ${money(leads.reduce((s,l)=>s+l.value,0))}</span></div>${leads.map(l=>`<article class="lead-card" draggable="true" ondragstart="dragLead(event,${l.id})"><h4>${escapeHTML(l.name)}</h4><p>${l.company?escapeHTML(l.company)+'<br>':''}${escapeHTML(l.event)}</p><div class="lead-meta"><span class="source ${l.source}">${l.source}</span><strong>${money(l.value)}</strong></div></article>`).join('')}</div>`}).join('')}</section></main>`); }
function setSource(v){state.sourceFilter=v;render()} function dragLead(e,id){e.dataTransfer.setData('text/plain',id)} function dropLead(e,stage){const id=Number(e.dataTransfer.getData('text/plain'));const l=state.leads.find(x=>x.id===id);if(l){l.stage=stage;save();render();toast(`${l.name} moved to ${stage}.`)}} function addLead(){const id=Math.max(...state.leads.map(l=>l.id))+1;state.leads.unshift({id,name:'New Catering Lead',company:'Demo Company',event:'Private event · 75 guests',value:3000,source:'organic',stage:'New Lead'});save();render();toast('Demo lead added to New Lead.')}

function render(){ state.route=location.hash.slice(1)||'home'; let html; if(state.route==='drop')html=drop(); else if(state.route==='checkout')html=checkout(); else if(state.route==='confirmation')html=confirmation(); else if(state.route==='seminole')html=seminole(); else if(state.route==='catering')html=catering(); else html=home(); document.querySelector('#app').innerHTML=html; if(state.route==='drop')startCountdown(); window.scrollTo({top:0,behavior:'instant'}); }
function startCountdown(){ clearInterval(window.dropTimer); const update=()=>{const now=new Date();let cutoff=new Date(now);cutoff.setDate(now.getDate()+((5-now.getDay()+7)%7));cutoff.setHours(15,0,0,0);if(cutoff<=now)cutoff.setDate(cutoff.getDate()+7);let n=Math.max(0,cutoff-now);const vals=[Math.floor(n/864e5),Math.floor(n%864e5/36e5),Math.floor(n%36e5/6e4),Math.floor(n%6e4/1000)];['days','hours','mins','secs'].forEach((k,i)=>{const el=document.querySelector(`#cd-${k}`);if(el)el.textContent=String(vals[i]).padStart(2,'0')})};update();window.dropTimer=setInterval(update,1000)}
window.addEventListener('hashchange',render); render();
